---
abstract: 'An easy way to use Log::Any in applications'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Find: 0
  File::Slurp: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102343, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Any-App
requires:
  Data::Dumper: 0
  File::HomeDir: 0
  File::Path: 2.07
  File::Slurp: 0
  File::Spec: 0
  Log::Any: 0.11
  Log::Any::Adapter: 0
  Log::Any::Adapter::Log4perl: 0
  Log::Dispatch::FileRotate: 0
  Log::Dispatch::Syslog: 0
  Log::Log4perl: 0
  perl: 5.010000
  vars: 0
resources:
  homepage: http://search.cpan.org/dist/Log-Any-App/
  repository: http://github.com/sharyanto/perl-Log-Any-App
version: 0.25
